### ISSUE TITLE
Data collection

### ISSUE THREAD

**Issue by hrlai** [ynshung/covid-19-malaysia#15]
Hello @ynshung thanks for such a fantastic compilation of data! The MOH portal is indeed not very transparent and accessible in terms of data availability and backcompatibility. 

I hope to fork your repo for casual graphing, mainly to provide secondary source of figures for friends and families to have a better grasp of the current situation that we're in. 

If this is okay with you, I have a few questions:
- what's your data entry/collection routine? Presumably that you do not manually (and painstackingly) enter the data, what's the percentage of data that's being automatically scrapped/mined? Just to get a ballpark idea.
- I might fill in the missing data here and there, as I go, but do you already have a general idea of where most data are missing/how more efficiently to spot them
- finally, I'd like to cite data contributor whenever possible in the figure caption---so how may I cite your effort here? (other than citing the primary data sources) 

Thanks again!

**Comment by ynshung** [comment]
Thank you for your interest towards the repo! This data is entirely open to all purposes so you are free to use it however you want :)

Regarding your questions:

(1) 0%. I typed all of the data in manually from the websites (almost) everyday. No automation is done so you might see a few delays here and there when the data is updated. One of the reason is that there are no easy way to extract data directly from the sources since they are *mostly* inconsistent and also most of it is in image form.

There's quite a lot of inconsistencies in the dataset. Such as import cases by districts that are sometimes included or not included in their images, combination of PUI & close contact cases, negative/pending cases type are not published around April but they do before, and cases by districts can decrease after a day? So backcompatibility is quite hard to handle in this case.

(2) First you can try searching by Google. Preferably the [official sources](https://github.com/ynshung/covid-19-malaysia#source), news sites are considerable but not statistics sites (such as MalaysiaKini or Outbreak.my, you can't be too sure of it sources). It's quite hard to find the missing one since there are no central source for all of it as they are scattered throughout the multiple sources and sometimes KKM just did not publish it. 

(3) You can link to the GitHub dataset page with its name (ynshung/covid-19-malaysia)

**Comment by hrlai** [comment]
Alright noted. I didn't expect to find someone sharing hand-entered data, so kudos for your effort! This is fantastic.

I'll take a look at this soon :-)
