### ISSUE TITLE
Daily negative cases from MOH

### ISSUE THREAD

**Issue by hrlai** [ynshung/covid-19-malaysia#17]
In your to-do there is "Daily negative cases from MOH". 

It seems that the only way to obtain daily number of tests, daily positive, and daily negative is from the table at the bottom of the MOH website ("Ringkasan Kes"). MOH seems to be transferring to a [new website](http://covid-19.moh.gov.my/), I am worried that the table will become unavailable if the [old website](https://www.moh.gov.my/index.php/pages/view/2019-ncov-wuhan) is taken off.

Since COVID-19 is going to stay for a while, it may still be useful if we start recording manually the:
1. total daily case tested
2. daily positive cases
3. daily negative cases = 1 - 2
from the table starting now. If you think so, I propose a new `csv` file with at least 4 columns: `date`, `test`, `positive`, and `negative`

**Comment by ynshung** [comment]
We can access the previous versions of the website with archive.org, but not all snapshots are available so news site may be the alternative reference. Though its seems like MOH doesn't always report their negative cases or tested numbers daily (or consistently, and the new website doesn't seem to contain the information in it). So it will be scouring through archive and news to find all the data since the beginning. DG Hisham may cover them in the daily press conference though.

**Comment by ynshung** [comment]
@hrlai This [new official repo](https://github.com/MoH-Malaysia/covid19-public/blob/main/epidemic/tests_malaysia.csv) have covered daily tests (from 2020 and also types of tests!). Take a look there!

**Comment by hrlai** [comment]
Thanks for the heads-up @ynshung and for persisting at this. Hope all is well on your side.
